### ISSUE TITLE
Issue: Unexpected Error on all models

### ISSUE THREAD

**Issue by Alikhan018** [ahadnawaz585/AI-Bot-WhatsApp-Integration-REST-API#2]
Hey ahad,
I cloned your repo and when i am using this code by npm run start 
its giving me this response and error on all models except the pdf model

![Screenshot 2024-08-05 at 3 00 01 PM](https://github.com/user-attachments/assets/adbc97c0-a3c9-41d8-819c-8aa7215801a9)
![Screenshot 2024-08-05 at 3 01 00 PM](https://github.com/user-attachments/assets/a53ca116-9ed9-4d1d-8317-27c1998e2d08)

**Comment by ahadnawaz585** [comment]
It is because you have not added API keys for the models we using . so the steps to do that is mention in [readme.md](https://github.com/ahadnawaz585/AI-Bot-WhatsApp-Integration-REST-API/blob/main/README.md) as :
Set up environment variables:
   - Rename `.env.example` to `.env`.
   - Generate an API key from the [Gemini](https://gemini.google.com/app)  and [Stability](https://stability.ai/news/api-platform-for-stability-ai) website and add it to the `.env` file.
  
   - ```dotenv
     # Gemini API Key
     GEMINI_API_KEY=your_gemini_api_key_here

     # Stability API Key
     STABILITY_API_KEY=your_stability_api_key_here
